### ISSUE TITLE
infer_mode still returns "REQUIRED" for json file

### ISSUE THREAD

**Issue by rconnol** [bxparks/bigquery-schema-generator#37]
I set infer_mode=False, and after scanning the json file, the resulting schema still had 'REQUIRED' fields instead of the default 'NULLABLE'.

Is that the expected behavior? Or am I misunderstanding what the argument does?

**Comment by bxparks** [comment]
Can you send a reproducible example with the exact flags that you are using? The `--infer_mode` is only meant only for CSV, so you should have gotten an error message if used with JSON.

**Comment by bxparks** [comment]
Closed due to lack of activity.
