### ISSUE TITLE
Sudo pip install is discouraged

### ISSUE THREAD

**Issue by alexwennerberg** [bxparks/bigquery-schema-generator#38]
Hey -- I love this tool. However, the documentation recommends using sudo to install pip packages, which is discouraged. See this stackoverflow thread: https://stackoverflow.com/questions/21055859/what-are-the-risks-of-running-sudo-pip

I would recommend altering the instructions to suggest `pip3 install --user`, which allows you to get the command line script outside a virtual environment without requiring you to install as root.

Thanks!

**Comment by bxparks** [comment]
That's a good point. Updated the README.md.
Python packaging is such a mess, and my Python environment so horribly messed up, I think installing as root is the only that works for me right now. Sigh
