### ISSUE TITLE
getting error after running the generate-schema

### ISSUE THREAD

**Issue by snowlover173** [bxparks/bigquery-schema-generator#41]
>generate-schema file2.data.json file.schema.json
usage: generate-schema [-h] [--input_format INPUT_FORMAT] [--keep_nulls]
                       [--quoted_values_are_strings] [--infer_mode]
                       [--debugging_interval DEBUGGING_INTERVAL]
                       [--debugging_map] [--sanitize_names]
generate-schema: error: unrecognized arguments: file2.data.json file.schema.json

I have tried linux and mac both and get the same error. the file2.data.json has only one json object. but basically it gives error on the args.

**Comment by bxparks** [comment]
The script reads from the STDIN and outputs to the STDOUT. See the first paragraph of the README (https://github.com/bxparks/bigquery-schema-generator):

"This script generates the BigQuery schema from the newline-delimited data records on the STDIN. The records can be in JSON format or CSV format. The BigQuery data importer (bq load) uses only the first 100 lines when the schema auto-detection feature is enabled. In contrast, this script uses all data records to generate the schema.

Usage:
```
$ generate-schema < file.data.json > file.schema.json
$ generate-schema --input_format csv < file.data.csv > file.schema.json
```
"
