### ISSUE TITLE
Loading GCP stackdriver logs into BQ

### ISSUE THREAD

**Issue by coffeecoco** [bxparks/bigquery-schema-generator#51]
Schema nested too deeply for field 

protoPayload.request.spec.validation.openAPIV3Schema.properties.spec.properties.match.properties.kinds.items.properties.apiGroups.items, maximum allowed depth is 15.

  "logName": "projects/xxxxxxxxxxxxx/logs/cloudaudit.googleapis.com%2Fdata_access",
  "type": "k8s_cluster"

Need a way to possibly handle this

**Comment by bxparks** [comment]
This does not look like an error from the `generate-schema` script. So I assume that this is from the `bq load` command? If so, I'm not able to help you.

**Comment by coffeecoco** [comment]
You need to handle this other wise your generator will fail you cannot create a schema that is nested 15 levels.


Ive made my own fix in in your code to resolve this.

**Comment by bxparks** [comment]
You need to give me some way to reproduce the bug. 
1) Upload a minimal sample data that triggers the bug. Or,
2) Paste the python stack trace. Or,
3) Send me a PR for your fix, preferably with a test case.
