### ISSUE TITLE
apply quoted_values_are_strings to timetstamps?

### ISSUE THREAD

**Issue by AlexFragotsis** [bxparks/bigquery-schema-generator#68]
Hello, I have a string column in BQ where I store timestamps. 

Is there a way to prevent deduce_schema converting my field that contains string-timestamps to timestamps if I have quoted_values_are_strings= True?

Or maybe another solution would be if I'm passing the original schema to have the option to prevent changing the types of the existing colums? e.g. add a flag dont_modify_original_colums and whenever it's true, don't modify the colums of the existing schema (only add new ones)

**Comment by bxparks** [comment]
Hi, I'm not sure I understand which behavior you want. Currently timestamps are always inside quotes, and they are always inferred, regardless of the `--quoted_values_are_strings` flag. Are you saying that you want to turn off the interpretation of timestamps? In other words, the current behavior is this:

```
$ cat quoted.data.json 
{ "qi" : "3", "qf": "2.0", "qb": "false", "qtime": "2021-04-21T07:54:00" }

$ generate-schema < quoted.data.json
[
  {
    "mode": "NULLABLE",
    "name": "qb",
    "type": "BOOLEAN"
  },
  {
    "mode": "NULLABLE",
    "name": "qf",
    "type": "FLOAT"
  },
  {
    "mode": "NULLABLE",
    "name": "qi",
    "type": "INTEGER"
  },
  {
    "mode": "NULLABLE",
    "name": "qtime",
    "type": "TIMESTAMP"
  }
]

$ generate-schema --quoted_values_are_strings < quoted.data.json
INFO:root:Processed 1 lines
[
  {
    "mode": "NULLABLE",
    "name": "qb",
    "type": "STRING"
  },
  {
    "mode": "NULLABLE",
    "name": "qf",
    "type": "STRING"
  },
  {
    "mode": "NULLABLE",
    "name": "qi",
    "type": "STRING"
  },
  {
    "mode": "NULLABLE",
    "name": "qtime",
    "type": "TIMESTAMP"
  }
]
```

Are you saying that you want `qtime` to be `STRING`? So you want something like `--quoted_values_are_strings_i_mean_everything_even_timestamps`?

With regards to the second part of your question, I thought that was already true, that if you start with an existing schema using `--existing_schema_path`, the existing schema is considered to be "HARD" internally, and the schema is not changed. Though that part of the code was added relatively recently, mostly through a Contributor, and certain parts were tricky to get right, and I don't have all of that logic in my head right now.

**Comment by AlexFragotsis** [comment]
@bxparks hey thanks for the quick response, yes that's what I'm looking for  `quoted_values_are_strings_i_mean_everything_even_timestamps `

and about the second one, I'm using it in python, I don't know if there's any difference or if I am doing something wrong

basically first I'm extracting the current schema from BigQuery
`generator = SchemaGenerator(input_format='dict', quoted_values_are_strings=True)
original_schema_map, original_schema_error_logs = generator.deduce_schema(input_data=original_schema)`

and then use it to generate the schema from the data I have
`schema_map, error_logs = generator.deduce_schema(input_data=batch, schema_map=original_schema_map)`

but in the new schema, some of the old fields are changing (specifically from String to Timestamp) as I explained above

**Comment by bxparks** [comment]
If you want to send me a PR for a `--quoted_date_time_timestamps_are_strings` flag, I'd be open to that. The logic happens in `infer_value_type()` method.

With regards to your second problem, I don't think that should be happening, but I'm not sure. Can you post a minimal reproducible example, containing sample data, the output produced by `generate-schema`, and what your expectation was?

(Just a heads up, I don't work on BigQuery stuff any more, and I don't have a lot of spare cycles to spend on this. I'm going to rely on you to do most of the debugging and development work.)

**Comment by AlexFragotsis** [comment]
@bxparks heyy, so turns out that I'm just stupid. I wasn't aware of the `read_existing_schema_from_file` and I was doing some weird things in the code and the `deduce_schema` wasn't working properly. I switched to this and it works fine now

```
table_file_name = f"original_schema_{self.bq_table}.json"
table = self.bq_client.get_table(table_id)
self.bq_client.schema_to_json(table.schema, table_file_name)
original_schema_map = read_existing_schema_from_file(table_file_name)

schema_map, error_logs = generator.deduce_schema(input_data=batch, schema_map=original_schema_map)
schema = generator.flatten_schema(schema_map)
```

and since it's working I don't see any need for the `quoted_date_time_timestamps_are_strings` anymore. 
Thanks and sorry for the ticket

**Comment by bxparks** [comment]
Excellent, glad you got it working
