### ISSUE TITLE
Column name must start with a letter or underscore

### ISSUE THREAD

**Issue by somanishivam** [bxparks/bigquery-schema-generator#89]
https://github.com/bxparks/bigquery-schema-generator/blob/11bf0a2bd90a4f00385528c13caef7c0d3125b87/bigquery_schema_generator/generate_schema.py#L250

sanitize logic allows numbers to start name of column.

**Comment by bxparks** [comment]
As far as I'm concerned, it is the responsibility of the dataset owner to clean up the data for BigQuery, it's not the job of this project. I don't have any motivation to work on this. But if you send a clean PR with good unit tests, I'll take a look.

**Comment by bxparks** [comment]
Just for completeness, there was a previous Discussion about this here:
https://github.com/bxparks/bigquery-schema-generator/discussions/84

The high level point is that this project is a schema generator, not a data sanitizer, so I consider this to be outside the scope of this project. I don't want to be in the business of trying to support every variation of how different people want to sanitize their own data.

Closing.
